export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let startTime = Date.now();
while (Date.now() - startTime < 10_000) {
  // block the event loop for a while
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
